name: Create Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Create archive
        run: |
          mkdir -p tmp/scripts tmp/script-opts
          cp mpv-lossless-cut.lua tmp/scripts/
          cp mpv-lossless-cut.conf tmp/script-opts/
          cd tmp
          zip -r ../mpv-lossless-cut.zip scripts script-opts

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" mpv-lossless-cut.zip --verify-tag --generate-notes
